name: solana_wallet_adapter
description: Dart implementation of Solana's Mobile Wallet Adapter Specification.
repository: https://github.com/merigo-labs/solana-wallet-adapter
issue_tracker: https://github.com/merigo-labs/solana-wallet-adapter/issues/new/choose
# NOTE: "Prefer living with a less-clean platform API than making a breaking change." 
# https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.4+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  solana_common: ^0.0.4
    # path: ../solana_common
  solana_wallet_adapter_android: ^0.0.2
    # path: ../solana_wallet_adapter_android
  solana_wallet_adapter_ios: ^0.0.2
    # path: ../solana_wallet_adapter_ios
  solana_wallet_adapter_platform_interface: ^0.0.2+1
    # path: ../solana_wallet_adapter_platform_interface
  solana_wallet_adapter_web: ^0.0.1
    # path: ../solana_wallet_adapter_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: solana_wallet_adapter_android
      ios:
        default_package: solana_wallet_adapter_ios
      web:
        default_package: solana_wallet_adapter_web